import { adminDb } from '../../../../lib/firebaseAdmin';
import { sendEmail } from '../../../../lib/nodemailer';
import { corsResponse, handleOptions } from '../../../../lib/cors';

export async function OPTIONS() {
  return handleOptions();
}

export async function POST(request) {
  try {
    const { userId, email, ip } = await request.json();

    if (!userId || !ip) {
      return corsResponse({ error: 'Missing userId or ip address' }, 400);
    }

    // Geolocation lookup
    let city = 'Local Development';
    let countryName = 'Localhost';
    let region = 'Local Network';

    const isLocal = ip === '127.0.0.1' || ip === '::1' || ip.startsWith('192.168.') || ip.startsWith('10.') || ip === 'mock-ip';
    
    if (!isLocal) {
      try {
        const geoResponse = await fetch(`https://ipapi.co/${ip}/json/`);
        if (geoResponse.ok) {
          const geoData = await geoResponse.json();
          city = geoData.city || 'Unknown City';
          countryName = geoData.country_name || 'Unknown Country';
          region = geoData.region || 'Unknown Region';
        }
      } catch (err) {
        console.error('IP Geolocation fetch error:', err);
      }
    }

    // Retrieve user document from Firestore
    const userRef = adminDb.collection('users').doc(userId);
    const userDoc = await userRef.get();

    if (!userDoc.exists) {
      return corsResponse({ error: 'User document not found' }, 404);
    }

    const userData = userDoc.data();
    const lastIP = userData.lastLoginIP || '';
    const displayName = userData.displayName || 'Progress Tracker User';

    let emailSent = false;
    let alertTriggered = false;

    // Trigger alert if last IP is known and different from the current IP
    if (lastIP && lastIP !== ip) {
      alertTriggered = true;
      const timestamp = new Date().toLocaleString();

      // Styled Google Security-like Email Template
      const emailHtml = `
        <div style="font-family: sans-serif; max-width: 500px; margin: 0 auto; padding: 24px; border: 1px solid #e5e7eb; border-radius: 12px; background-color: #ffffff; color: #1f2937;">
          <div style="text-align: center; margin-bottom: 24px;">
            <span style="font-size: 28px; font-weight: bold; color: #534ab7;">Stitch</span>
            <span style="font-size: 28px; font-weight: bold; color: #10b981;">XP</span>
          </div>
          <h2 style="font-size: 20px; font-weight: 600; color: #dc2626; margin-top: 0;">New Login Detected</h2>
          <p style="font-size: 15px; line-height: 1.5; color: #4b5563;">Hello ${displayName},</p>
          <p style="font-size: 15px; line-height: 1.5; color: #4b5563;">We detected a new login to your account from a device or location we don't recognize:</p>
          <div style="background-color: #f9fafb; padding: 16px; border-radius: 8px; margin: 20px 0; border: 1px solid #f3f4f6;">
            <table style="width: 100%; font-size: 14px;">
              <tr>
                <td style="padding: 4px 0; font-weight: 600; color: #6b7280; width: 100px;">IP Address:</td>
                <td style="padding: 4px 0; color: #1f2937; font-family: monospace;">${ip}</td>
              </tr>
              <tr>
                <td style="padding: 4px 0; font-weight: 600; color: #6b7280;">Location:</td>
                <td style="padding: 4px 0; color: #1f2937;">${city}, ${region}, ${countryName}</td>
              </tr>
              <tr>
                <td style="padding: 4px 0; font-weight: 600; color: #6b7280;">Time:</td>
                <td style="padding: 4px 0; color: #1f2937;">${timestamp}</td>
              </tr>
            </table>
          </div>
          <p style="font-size: 14px; line-height: 1.5; color: #4b5563; margin-bottom: 24px;">If this was you, you can safely ignore this email. If you do not recognize this activity, please reset your password immediately to secure your account.</p>
          <hr style="border: 0; border-top: 1px dashed #e5e7eb; margin: 24px 0;" />
          <div style="text-align: center; font-size: 12px; color: #9ca3af;">
            This security email was auto-generated by StitchXP Progress Tracker.
          </div>
        </div>
      `;

      try {
        await sendEmail({
          to: email || userData.email,
          subject: 'StitchXP Security Alert: New Login Detected',
          html: emailHtml
        });
        emailSent = true;

        // Save a system notification in Firestore
        const notificationRef = adminDb.collection('notifications').doc();
        await notificationRef.set({
          id: notificationRef.id,
          userId,
          title: 'New Login Detected',
          body: `Login from a new IP: ${ip} (${city}, ${countryName})`,
          type: 'security_ip',
          read: false,
          createdAt: new Date().toISOString()
        });
      } catch (err) {
        console.error('Failed to send security alert email:', err);
      }
    }

    // Update the lastLoginIP and updatedAt in Firestore
    await userRef.update({
      lastLoginIP: ip,
      updatedAt: new Date().toISOString()
    });

    return corsResponse({
      success: true,
      alertTriggered,
      emailSent,
      city,
      countryName
    });

  } catch (error) {
    console.error('IP Security Route error:', error);
    return corsResponse({ error: error.message }, 500);
  }
}
