import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Task {
  id: string;
  title: string;
  description: string;
  category: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  dueDate: string;
  completed: boolean;
}

export const exportToExcel = (tasks: Task[]) => {
  const data = tasks.map((t) => ({
    'Task Name': t.title,
    'Description': t.description,
    'Category': t.category,
    'Priority': t.priority.toUpperCase(),
    'Due Date': t.dueDate,
    'Status': t.completed ? 'COMPLETED' : 'INCOMPLETE',
  }));

  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Stitch Progress');

  const colWidths = [{ wch: 25 }, { wch: 30 }, { wch: 15 }, { wch: 10 }, { wch: 15 }, { wch: 12 }];
  worksheet['!cols'] = colWidths;

  XLSX.writeFile(workbook, 'Stitch_Progress_Report.xlsx');
};

export const exportToPdf = (tasks: Task[], username: string) => {
  const doc = new jsPDF();

  doc.setFont('courier', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(83, 74, 183);
  doc.text('STITCHXP PRODUCTIVITY REPORT', 14, 20);

  doc.setFontSize(10);
  doc.setFont('courier', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by: ${username}`, 14, 26);
  doc.text(`Date of Audit: ${new Date().toLocaleDateString()}`, 14, 31);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, 36, 196, 36);

  const tableRows = tasks.map((t) => [
    t.title,
    t.category,
    t.priority.toUpperCase(),
    t.dueDate,
    t.completed ? 'COMPLETED' : 'INCOMPLETE',
  ]);

  autoTable(doc, {
    head: [['Task Name', 'Category', 'Priority', 'Due Date', 'Status']],
    body: tableRows,
    startY: 42,
    theme: 'grid',
    styles: { font: 'courier', fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [83, 74, 183], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 250] },
  });

  doc.save('Stitch_Progress_Report.pdf');
};
